# alpha.yml
name: develop

on:
  pull_request:
    branches:
       - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ckeckcout source code
        uses: actions/checkout@v3
      
      - name: npm install
        run: npm install
        
      - name: build
        run: npm run build
        
      - name: deploy
        env: 
          AWS_ACCESS_KEY_ID: '${{ }}'
          AWS_SECRET_ACCESS_KEY: '${{ }}'
        run: aws s3 sync ./dist s3://beta.clock.com
        
      - name: invalidation
        run: aws cloudfront create-invalidation --distribution-id E15G3RVA2Z4N1W --paths /*
