# alpha.yml
name: develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ckeckcout source code
        uses: actions/checkout@v3
      
      - name: npm ci
        run: npm ci
        
      - name: build
        run: npm run build
        
      - name: deploy
        env: 
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_S3_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}'
        run: aws s3 sync --region ap-northeast-2 ./dist s3://beta.clock.com
        
#       - name: invalidation
#         run: aws cloudfront create-invalidation --distribution-id E15G3RVA2Z4N1W --paths /*
